In [1]:
import numpy as np
import pandas as pd
import yfinance as yf

# Data

In [3]:
univ = ['AAPL', 'MSFT', 'GOOG', 'AMZN']
test_data = yf.download(univ, start='2025-10-01')

[*********************100%***********************]  4 of 4 completed

In [6]:
test_data.head(5)

Price            Close                                            High  \
Ticker            AAPL        AMZN        GOOG        MSFT        AAPL
Date
2025-10-01  255.202606  220.630005  245.379898  518.739136  258.539383
2025-10-02  256.880981  222.410004  246.269318  514.776550  257.929952
2025-10-03  257.770111  219.509995  246.289307  516.383484  258.988931
2025-10-06  256.441406  220.899994  251.346008  527.582581  258.819106
2025-10-07  256.231628  221.779999  246.968872  523.001099  257.150720

Price                                                  Low              \
Ticker            AMZN        GOOG        MSFT        AAPL        AMZN
Date
2025-10-01  222.149994  246.988849  519.537629  254.683106  216.610001
2025-10-02  222.809998  247.473534  520.625589  253.903857  218.949997
2025-10-03  224.199997  246.956870  519.517632  253.704061  219.339996
2025-10-06  221.729996  252.035561  530.038007  254.802995  216.029999
2025-10-07  222.889999  251.385988  528.810233  255.182627  220.169998

Price                                     Open                          \
Ticker            GOOG        MSFT        AAPL        AMZN        GOOG
Date
2025-10-01  239.044035  510.734099  254.793000  217.360001  241.022740
2025-10-02  242.946489  509.726005  256.331496  221.009995  245.479839
2025-10-03  242.311906  514.037898  254.423365  223.440002  245.070101
2025-10-06  245.529811  517.231958  257.740135  221.000000  245.619749
2025-10-07  246.649073  520.465866  256.561295  220.880005  248.767686

Price                     Volume
Ticker            MSFT      AAPL      AMZN      GOOG      MSFT
Date
2025-10-01  513.838274  48713900  43933800  23967700  22632300
2025-10-02  516.673025  42630200  41258600  20657500  21222900
2025-10-03  516.133951  49155600  43639000  19941400  15112300
2025-10-06  517.641165  44664100  43690900  18309000  21388600
2025-10-07  527.303044  31955800  31194700  13811200  14615200

In [ ]:
test_data.tail(5)

Price            Close                                            High  \
Ticker            AAPL        AMZN        GOOG        MSFT        AAPL
Date
2025-12-19  273.670013  227.350006  308.609985  485.920013  274.600006
2025-12-22  270.970001  228.429993  311.329987  484.920013  273.880005
2025-12-23  272.359985  232.139999  315.679993  486.850006  272.500000
2025-12-24  273.809998  232.380005  315.670013  488.019989  275.429993
2025-12-26  273.399994  232.520004  314.959991  487.709991  275.369995

Price                                                  Low              \
Ticker            AMZN        GOOG        MSFT        AAPL        AMZN
Date
2025-12-19  229.130005  308.989990  487.850006  269.899994  225.580002
2025-12-22  229.479996  311.700012  488.730011  270.510010  226.710007
2025-12-23  232.449997  316.299988  487.829987  269.559998  228.729996
2025-12-24  232.949997  316.290009  489.160004  272.200012  231.330002
2025-12-26  232.990005  316.559998  488.119995  272.859985  231.179993

Price                                     Open                          \
Ticker            GOOG        MSFT        AAPL        AMZN        GOOG
Date
2025-12-19  302.339996  482.489990  272.149994  226.759995  303.269989
2025-12-22  306.589996  482.690002  272.859985  228.610001  311.225006
2025-12-23  310.750000  484.739990  270.839996  229.059998  311.135010
2025-12-24  313.320007  484.829987  272.339996  232.130005  316.149994
2025-12-26  313.720001  485.959991  274.160004  232.039993  315.920013

Price                      Volume
Ticker            MSFT       AAPL      AMZN      GOOG      MSFT
Date
2025-12-19  487.359985  144632000  85544400  45234400  70836100
2025-12-22  486.119995   36571800  32261300  14091400  16963000
2025-12-23  484.980011   29642000  29230200  13961400  14683600
2025-12-24  485.679993   17910600  11420500   6138200   5855900
2025-12-26  486.709991   21455300  15948200   6714300   8822100

In [ ]:
test_data.loc['2025-12-23':'2025-12-26']

Price            Close                                            High  \
Ticker            AAPL        AMZN        GOOG        MSFT        AAPL
Date
2025-12-23  272.359985  232.139999  315.679993  486.850006  272.500000
2025-12-24  273.809998  232.380005  315.670013  488.019989  275.429993
2025-12-26  273.399994  232.520004  314.959991  487.709991  275.369995

Price                                                  Low              \
Ticker            AMZN        GOOG        MSFT        AAPL        AMZN
Date
2025-12-23  232.449997  316.299988  487.829987  269.559998  228.729996
2025-12-24  232.949997  316.290009  489.160004  272.200012  231.330002
2025-12-26  232.990005  316.559998  488.119995  272.859985  231.179993

Price                                     Open                          \
Ticker            GOOG        MSFT        AAPL        AMZN        GOOG
Date
2025-12-23  310.750000  484.739990  270.839996  229.059998  311.135010
2025-12-24  313.320007  484.829987  272.339996  232.130005  316.149994
2025-12-26  313.720001  485.959991  274.160004  232.039993  315.920013

Price                     Volume
Ticker            MSFT      AAPL      AMZN      GOOG      MSFT
Date
2025-12-23  484.980011  29642000  29230200  13961400  14683600
2025-12-24  485.679993  17910600  11420500   6138200   5855900
2025-12-26  486.709991  21455300  15948200   6714300   8822100